### ISSUE TITLE
[HOME] Visit Mountaineer Country logo link

### ISSUE THREAD

**Issue by GeoWoodstockXXI** [kkudlak45/gwxxi#38]
I have permission from the Visit Mountaineer Country CVB to change the link from the grants page to their homepage. Clicking on the "VISIT MOUNTAINEER COUNTRY.COM" button should take people to https://www.visitmountaineercountry.com

**Comment by GeoWoodstockXXI** [comment]
![VMC Transparent](https://github.com/user-attachments/assets/3c672aef-b3a6-440b-af66-6f0bd39a6d4d)

Adding transparent png 1:1

**Comment by kkudlak45** [comment]
white background is fine as well. to be honest it could be better. really doesn't matter because our background is white. only matters if you think we'll want to change the bg color and would want the logo to blend in.

thinking back, we have a border around these images so white background is probably better

**Comment by kkudlak45** [comment]
![Screenshot 2024-09-20 at 10 48 17 AM](https://github.com/user-attachments/assets/911846f4-4f0a-4aaa-ba4d-518f632eb8d8)
